<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('services')->delete();
        
        \DB::table('services')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Ceramic Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Graphene Coating',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'PPF',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'single',
                'flat_price' => '5500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'single',
                'flat_price' => '6000.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'single',
                'flat_price' => '7000.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:42',
                'updated_at' => '2026-09-27 13:32:42',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Interior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'single',
                'flat_price' => '8500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'single',
                'flat_price' => '5500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'single',
                'flat_price' => '6000.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'single',
                'flat_price' => '6500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'single',
                'flat_price' => '7000.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'single',
                'flat_price' => '7500.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Exterior Detailing',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'single',
                'flat_price' => '8000.00',
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Washover',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Hatchback',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sedan',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Coupe',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Crossover',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'MPV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Wagon',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Sports Car',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'SUV',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Pickup Truck',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Undercoat',
                'description' => NULL,
                'notice' => NULL,
                'vehicle_type' => 'Van',
                'selection_type' => 'multi',
                'flat_price' => NULL,
                'pricing_matrix' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-27 13:32:43',
                'updated_at' => '2026-09-27 13:32:43',
            ),
        ));
        
        
    }
}